name: Sync Fork

on:
  schedule:
    - cron: '5 */6 * * *' # Every 6th hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: AdguardTeam
          base: gh-pages
          head: gh-pages
          ignore_fail: true
